[package]
name = "rediscovering-tomography"
version = "0.1.0"
authors = ["Simon Frankau <sgf@arbitrary.name>"]
edition = "2018"

[dependencies]
nalgebra = "*"
image = "*"
clap = "3.0.0-beta.4"
rustfft = "*"
itertools = "*"
